[1주차] 객체지향 코드 연습(Hoya324)
COW-edu/practice-oop-lotto pull request #1
Opened 2023-07-07 08:08 UTC by Hoya324

[1주차] 객체지향 코드 연습 - 로또 구현 코드입니다.

2023-07-07 15:33 UTC, dojinyou requested changes
전체적인 구조도(클래스의 관계)에 대해서 PR에 첨부해주면 좋을 듯!

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/message/ResultMessage.java
> +        return SIX_CORRECT;
이렇게 쓸꺼면 Enum winningCount 필드가 필요 없어 보임.

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/message/ResultMessage.java
> +        return SIX_CORRECT;
이런 형태라면 향상된 swtich 이 좋음

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/model/LottoNumberRepository.java
> +    private static final List<List<Integer>> lottoList = new ArrayList<>();
멀티쓰레드 환경에서 동시에 여러 쓰레드가 add하게 되면 어떤 현상이 벌어질까요?

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/model/LottoResultRepository.java
> +    private static final int [] lottoResult = new int[5];
naming convenction 체크

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +    private final LottoResultRepository lottoResultRepository = new LottoResultRepository();
외부 주입해주기

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +    private final LottoResultRepository lottoResultRepository = new LottoResultRepository();
각 도메인들간의 관계 정의하기

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +        } else if (isNotDivided1000) {
else 안 쓰기

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +        for (int count = 0; count < purchasedLottoCounts; count++) {
변수명 count 굿

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +            integerWinningNumber.add(integerLottoNumber);
winningNumber 개수에 대한 검증은 없어도 되나요?

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/service/LottoService.java
> +        }
이런 형태라면 foreach문이 나을 수도

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/view/InputView.java
> +        System.out.println(message.getMessage());
outputView의 역할이랑 어떤 차이인지?

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
inputView의 역할이 무엇인지? 지금은 좀 섞여 있는 듯?

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/view/OutputView.java
> +            System.out.println(lottoList.get(index));
출력해야될 문자열을 모아서 출력하지 않는 이유는?

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/view/OutputView.java
> +    private final int RESULT_INDEX_SEVEN = 7;
변수명에 값의 의미를 담으면 좋을듯

2023-07-07 15:33 UTC, dojinyou commented on src/test/java/lotto/LottoTest.java
> +    }
`@ParameterizedTest`를 이용해서 테스트 케이스 분리하기

2023-07-07 15:33 UTC, dojinyou commented on src/test/java/lotto/LottoTest.java
> +    }
의미 있는 값 사용하기 `90`은 의미가 너무 적음

2023-07-07 15:33 UTC, dojinyou commented on src/main/java/lotto/view/OutputView.java
> +        ResultMessage resultMessage;
변수의 범위 최소화 하기

2023-07-07 15:34 UTC, dojinyou requested changes
전체적인 구조도(클래스의 관계)에 대해서 PR에 첨부해주면 좋을 듯!

2023-07-07 15:34 UTC, dojinyou requested changes
전체적인 구조도(클래스의 관계)에 대해서 PR에 첨부해주면 좋을 듯!

2023-07-07 15:45 UTC, Hoya324 commented on src/main/java/lotto/message/ResultMessage.java
> +        return SIX_CORRECT;
switch 문을 사용하지 말라는 요구사항이 있었는데 Enum을 빼고 다시 짜는게 나을까요??

2023-07-07 15:54 UTC, Hoya324 commented on src/main/java/lotto/controller/LottoController.java
> +    public int [] countWinningNumber(int purchasedLottoCounts) {
Array의 크기를 설정해주면 초기값이 0으로 설정되는 것을 생각했을 때 더 간결할 것 같다고 생각해서 Array를 사용했습니다!

2023-07-07 16:05 UTC, Hoya324 commented on src/main/java/lotto/Lotto.java
> +        }
[Java Enum 활용기](https://techblog.woowahan.com/2527/) 
위 글과 활용 방법은 많이 상이하지만, 사용자에게 입력받는 메세지, 출력할 메세지, 결과 메세지 등 여러 메세지를 관리할 때 하나의 클래스에서 관리하면 편할 것 같다고 생각이 들었습니다. 또한 결과 메세지를 출력할 때 해당하는 등수(특히, 보너스 번호를 맞춘 경우)에 맞는 메세지를 출력해줘야 할 때, 내부 메서드로 판단하여 내보내는 것이 기능을 더 나눌 수 있다고 생각했습니다!

2023-07-07 16:09 UTC, Hoya324 commented on src/main/java/lotto/controller/LottoController.java
> +        return lottoService.calculatePurchaseAmount(purchaseAmount, oneThousand);
매직 넘버라고 판단했는데 개념이 부족했나봅니다! 더 공부해보겠습니다.

2023-07-07 16:48 UTC, Hoya324 commented on src/main/java/lotto/service/LottoService.java
> +            integerWinningNumber.add(integerLottoNumber);
Lotto 클래스에서 검사합니다..!

2023-07-07 16:55 UTC, Hoya324 commented on src/main/java/lotto/view/InputView.java
> +        System.out.println(message.getMessage());
inputView는 구입금액, 당첨 번호, 보너스 번호를 사용자가 입력 받을 때 보내는 메세지를 보여주는 클래스이고,
outputView는 구입한 로또를 개수만큼 출력, 당첨 통계를 출력하는 역할을 합니다!

2023-07-08 13:18 UTC, 5uhwann reviewed
👍

2023-07-08 13:18 UTC, 5uhwann commented on src/main/java/lotto/controller/LottoController.java
> +        int oneThousand = 1000;
좀 더 의미있는 변수명 사용해주세요.

2023-07-08 13:18 UTC, 5uhwann commented on src/main/java/lotto/controller/LottoController.java
> +    public List<List<Integer>> createLottoList(int purchasedLottoCounts) {
[일급 컬렉션 관련 글](https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/)

2023-07-08 13:18 UTC, 5uhwann commented on src/main/java/lotto/message/ResultMessage.java
> +        return SIX_CORRECT;
로또 당첨 결과를 계산하는 책임이 RsultMessage 클래스에 있는게 좋은지 고민해보세요.

2023-07-08 13:18 UTC, 5uhwann commented on src/main/java/lotto/view/InputView.java
> +    }
구매 금액 입력에 대한 검증이 단순히 숫자이기만 하면 통과되는게 맞는지 고민해보세요.

2023-07-08 13:18 UTC, 5uhwann commented on src/main/java/lotto/view/OutputView.java
> +    public void rateOfLotteryWinnings(OutputMessage outputMessage, String totalWinningMoney) {
```suggestion
    public void outPutRateOfLotteryWinnings(OutputMessage outputMessage, String totalWinningMoney) {
```

2023-07-08 13:20 UTC, 5uhwann commented on src/main/java/lotto/Lotto.java
> +        }
private 메서드는 보통 public 메서드 하단에 작성합니다.

2023-07-08 13:21 UTC, 5uhwann commented on src/main/java/lotto/controller/LottoController.java
> +        int oneThousand = 1000;
좀 더 의미있는 변수명 사용해주세요.

2023-07-15 08:56 UTC, Hoya324 commented on src/main/java/lotto/controller/LottoController.java
> +        int oneThousand = 1000;
변경 완료했습니다!

2023-07-15 08:57 UTC, Hoya324 commented on src/main/java/lotto/view/InputView.java
> +    }
추가적인 예외처리가 있었으나 한 곳에 배치되어있지 않아 가독성이 떨어진다고 판단하여 한 곳으로 옮겼습니다!

2023-07-15 09:29 UTC, Hoya324 commented on src/main/java/lotto/controller/LottoController.java
> +    public List<Integer> insertWinningLottoNumbers(String winningNumbers) throws IllegalArgumentException {
수정해서 다시 올렸습니다!

2023-07-16 15:53 UTC, 5uhwann reviewed
enum을 활용할 방법에 대해 조금더 고민해보세요~

2023-07-16 15:53 UTC, 5uhwann commented on src/main/java/lotto/domain/Lotto.java
> +  }
public 메서드는 private 메서드보다 상단에 작성해주세요.

2023-07-16 15:53 UTC, 5uhwann commented on src/main/java/lotto/controller/LottoControllerImpl.java
> +    return lottoService.calculatePurchaseAmount(purchaseAmount, 1000);
1000 이라는 값이 무슨 의미인지 확인 하기 어렵습니다. 의미 있는 이름으로 바꿔주세요. 더해서 해당 값이 고정된 값이라면 메서드 인자로 넘기기 보단 calculatePurchaseAmount 메서드에서 메서드 레벨 변수로 사용하는것이 좋아보입니다.

2023-07-16 15:53 UTC, 5uhwann commented on src/main/java/lotto/domain/Lotto.java
> +  private static final int LOTTO_RANK_5 = 5;
정적 멤버 변수는 클래스 최상단에 위치해주세요.

2023-07-16 15:53 UTC, 5uhwann commented on src/main/java/lotto/domain/WinningLottoImpl.java
> +  private static List<Integer> winningNumber;
static인 이유가 무엇인가요?

2023-07-16 15:53 UTC, 5uhwann commented on src/main/java/lotto/view/InputView.java
> +    System.out.println();
InputView 클래스에서 println을 하는 것보단 OutputView에서 출력을 처리하는게 좋아 보입니다.

2023-07-17 09:00 UTC, wonjunYou commented on src/test/java/lotto/LottoTest.java
> +  void createLottoByDuplicatedNumber(int number1, int number2) {
테스트 코드 이름 작성시에는 한글, 영문 중 하나로만 일관적으로 작성해주시는 것이 좋습니다!

2023-07-17 09:02 UTC, wonjunYou reviewed
고생하셨습니다! 경호님~ 점점 실력이 늘어가시는 게 보여서 좋네요 ㅎ 읽다 보니 재미있어서 좀 더 빡세게 리뷰해봤습니다 ㅎㅅㅎ 도움이 되셨으면 좋겠습니다!

2023-07-17 09:57 UTC, Hoya324 commented on src/main/java/lotto/message/InputMessage.java
> +    INPUT_PURCHASE_AMOUNT("구입금액을 입력해 주세요."),
원래는 관련 메세지가 많으면 한번에 관리하는 것이 편하고 추후에 메세지에 변동이 생기면 찾기 쉬울 것 같다는 생각으로 모아서 관리하였는데, 로또에서는 메세지가 많지 않아 메세지는 따로 처리해야하는지 고민 중입니다! 어떻게 하는게 나을까요..?

2023-07-17 10:07 UTC, Hoya324 commented on src/main/java/lotto/domain/WinningLottoImpl.java
> +  private static List<Integer> winningNumber;
static으로 하지 않기 위해 몇 가지 시도를 해보았는데, 원하는 것처럼 되지 않아서 일단 static으로 제출했습니다..! 다시 수정해보겠습니다!

2023-07-18 13:03 UTC, wonjunYou commented on src/main/java/lotto/message/InputMessage.java
> +    INPUT_PURCHASE_AMOUNT("구입금액을 입력해 주세요."),
사실 이것도 정답은 없지만, 제 생각은 결국 메세지도 메세지를 사용하는 책임을 가진 객체 내에서 관리해야 한다고 생각합니다! 만약 여러 객체가 함께 사용하는 메세지라면 공통적으로 관리하구요.

2023-09-19 00:46 UTC, merged