[3주차] 객체지향 코드 연습(jina4066)
COW-edu/practice-oop-lotto pull request #20
Opened 2023-10-10 12:40 UTC by jina4066

2023-10-10 14:01 UTC, dojinyou commented on src/main/java/lotto/model/Lotto.java
> +        if (numbers.size() != 6) {
매직 넘버

2023-10-10 14:02 UTC, dojinyou requested changes
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-10 14:02 UTC, dojinyou requested changes
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-10 14:02 UTC, dojinyou requested changes
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-10 14:02 UTC, dojinyou reviewed
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-10 14:02 UTC, dojinyou requested changes
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-10 14:02 UTC, dojinyou requested changes
불필요한 static이나 중복된 데이터들이 많은 것 같아요. Java Collections에 대한 이해가 있으면 더 좋을 것 같습니다.
객체 설계와 책임에 대해서 조금 더 고민해보면 좋을 것 같아요

2023-10-12 15:35 UTC, wonjunYou reviewed
코드 퀄리티가 많이 좋아졌습니다..! 이대로 갑시다~

2023-10-12 15:35 UTC, wonjunYou commented on src/main/java/lotto/LottoGenerator.java
> +    return lottos;
```suggestion
    List<Lotto> lottos = new ArrayList<>();
    
    for (int i = 0; i < count; i++) {
      List<Integer> selectedNumbers = Randoms.pickUniqueNumbersInRange(LOTTO_MIN_NUMBER, LOTTO_MAX_NUMBER, LOTTO_SIZE);
      Collections.sort(selectedNumbers);
      lottos.add(new Lotto(selectedNumbers));
    }
    
    return lottos;
```

2023-10-12 15:35 UTC, wonjunYou commented on src/main/java/lotto/LottoResult.java
> +    }
줄바꿈이 필요합니다...! 또한 함수가 여러 역할을 하는 것 같은데 조금 더 분리해주세요!

2023-10-12 15:35 UTC, wonjunYou commented on src/main/java/lotto/model/Ranking.java
> +}
private 메서드는 public 메서드 아래에 위치시켜주세요!

또한 MVC에서 도메인(모델)과 View는 서로 몰라야 합니다!

2023-10-16 12:01 UTC, jina4066 commented on src/main/java/lotto/Lotto.java
> +        if (numbers.stream().distinct().count() != 6) {
수정하겠습니다!!

2023-10-16 12:06 UTC, jina4066 commented on src/main/java/lotto/LottoInput.java
> +    if (money % 1000 != 0) {
매직넘버 더 잘 확인하여 수정하겠습니다! :)

2023-10-16 12:06 UTC, jina4066 commented on src/main/java/lotto/LottoInput.java
> +    if (winningNumbers.size() != 6) {
넵!

2023-10-16 12:15 UTC, jina4066 commented on src/main/java/lotto/controller/LottoController.java
> +    }
for-each문을 사용하는 것이 훨씬 간결하고 읽기 쉬운 것 같네요. 수정하겠습니다!

2023-10-16 12:19 UTC, jina4066 commented on src/main/java/lotto/controller/LottoController.java
> +    Ranking rank;
rank가 반복문 안에서만 사용되니 반복문 안에서 선언하고 사용하도록 수정하겠습니다!

2023-10-16 12:38 UTC, jina4066 commented on src/main/java/lotto/controller/LottoController.java
> +    return result;
네! EnumMap으로 수정하겠습니다!

2023-10-16 12:48 UTC, jina4066 commented on src/main/java/lotto/LottoGenerator.java
> +  public static List<Lotto> generateLotto(int count) {
네!! 수정하여 반영하도록 하겠습니다!

2023-10-16 12:48 UTC, jina4066 commented on src/main/java/lotto/LottoInput.java
> +  }
넵!

2023-10-16 15:37 UTC, jina4066 commented on src/main/java/lotto/LottoInput.java
> +    System.out.println("당첨 번호를 입력해주세요.");
넵! 출력에 해당하는 부분은 OutputView에게 맡기도록 하겠습니다!

2023-10-16 15:58 UTC, jina4066 commented on src/main/java/lotto/model/Lotto.java
> +        if (numbers.size() != 6) {
매직 넘버 명심하겠습니다...!

2024-09-27 02:58 UTC, closed without merging